-- TẠO TRIGGER TỰ ĐỘNG TẠO ID CHO NHÂN VIÊN VỚI FORMAT: NV***

DELIMITER //

CREATE TRIGGER trg_before_insert_nhanviens
BEFORE INSERT ON NHANVIENS
FOR EACH ROW
BEGIN
    DECLARE next_id INT;
    DECLARE formatted_id VARCHAR(255);

    SELECT IFNULL(MAX(CAST(SUBSTRING(MANHANVIEN, 3, 3) AS UNSIGNED)), 0) + 1 
    INTO next_id 
    FROM NHANVIENS;

    SET formatted_id = CONCAT('NV', LPAD(next_id, 3, '0'));

    IF NEW.MANHANVIEN IS NULL OR NEW.MANHANVIEN = '' THEN
        SET NEW.MANHANVIEN = formatted_id;
    END IF;
END;

//
DELIMITER ;

INSERT INTO CHUCVUS (MACHUCVU, TENCHUCVU, TRANGTHAI)
VALUES ('CV001', 'QuanTriVien', true),
		('CV002', 'NhanVienTuyenSinh', true),
        ('CV003', 'CongTacVien', true),
        ('CV004', 'NhanVienKeToan', true);


-- TEST 
INSERT INTO NHANVIENS (TENNHANVIEN, NGAYSINH, GIOITINH, SOCMND, SODIENTHOAI, EMAIL, DIACHI, MACHUCVU, NGUOINHAPTHONGTIN, GHICHU, URIHINHDAIDIEN)
VALUES 
('Nguyen Van A', '1995-06-15', 1, '123456789', '0987654321', 'a@example.com', 'Hanoi', 'CV001', 'Admin', 'Ghi chú A', 'avatar1.jpg'),
('Tran Thi B', '1998-09-20', 0, '987654321', '0912345678', 'b@example.com', 'Ho Chi Minh', 'CV001', 'Admin', 'Ghi chú B', 'avatar2.jpg'),
('Le Van C', '2000-01-10', 1, '567890123', '0934567890', 'c@example.com', 'Da Nang', 'CV001', 'Admin', 'Ghi chú C', 'avatar3.jpg');

SELECT * FROM NHANVIENS;
SELECT * FROM CHUCVUS;

DELETE FROM NHANVIENS;
DELETE FROM CHUCVUS;

-- TẠO TRIGGER TỰ ĐỘNG TẠO ID CHO GIẢNG VIÊN VỚI FORMAT: GV***

DELIMITER //

CREATE TRIGGER trg_before_insert_giangviens
BEFORE INSERT ON GIANGVIENS
FOR EACH ROW
BEGIN
    DECLARE next_id INT;
    DECLARE formatted_id VARCHAR(255);

    SELECT IFNULL(MAX(CAST(SUBSTRING(MAGIANGVIEN, 3, 3) AS UNSIGNED)), 0) + 1 
    INTO next_id 
    FROM GIANGVIENS;

    SET formatted_id = CONCAT('GV', LPAD(next_id, 3, '0'));

    IF NEW.MAGIANGVIEN IS NULL OR NEW.MAGIANGVIEN = '' THEN
        SET NEW.MAGIANGVIEN = formatted_id;
    END IF;
END;

//

DELIMITER ;

INSERT INTO LINHVUCS (MALINHVUC, TENLINHVUC)
VALUES ('LV001', 'Lập trình Web (Frontend, Backend, Fullstack)'),
	   ('LV002', 'Lập trình Mobile (Android, iOS, Cross-platform)'),
       ('LV003', 'SQL (MySQL, PostgreSQL, SQL Server)'),
       ('LV004', 'DevOps & CI/CD'),
       ('LV005', 'Mạng máy tính & An ninh mạng');
       
SELECT * FROM LINHVUCS;

SELECT * FROM GIANGVIENS;

-- TẠO TRIGGER TỰ ĐỘNG TẠO ID CHO PHONGHOC VỚI FORMAT: PH***

DELIMITER //

CREATE TRIGGER trg_before_insert_phonghoc
BEFORE INSERT ON PHONGHOCS
FOR EACH ROW
BEGIN
    DECLARE max_id INT;
    DECLARE new_id VARCHAR(255);

    SELECT IFNULL(MAX(CAST(SUBSTRING(MAPHONGHOC, 3, 3) AS UNSIGNED)), 0) + 1 
    INTO max_id 
    FROM PHONGHOCS 
    WHERE MAPHONGHOC REGEXP '^PH[0-9]{3}$';

    SET new_id = CONCAT('PH', LPAD(max_id, 3, '0'));

    IF NEW.MAPHONGHOC IS NULL OR NEW.MAPHONGHOC = '' THEN
        SET NEW.MAPHONGHOC = new_id;
    END IF;
END;

//

DELIMITER ;

SELECT CONCAT('PH', LPAD(IFNULL(MAX(CAST(SUBSTRING(MAPHONGHOC, 3, 3) AS UNSIGNED)), 0) + 1, 3, '0')) FROM PHONGHOCS;

SELECT * FROM PHONGHOCS;

SELECT * FROM PHONGHOCS WHERE TENPHONGHOC LIKE '%P%';

-- XỬ LÝ KHÓA HỌC - KHOAHOCS

SELECT CONCAT('KH', LPAD(IFNULL(MAX(CAST(SUBSTRING(MAKHOAHOC, 3, 3) AS UNSIGNED)), 0) + 1, 3, '0')) FROM KHOAHOCS; 

SELECT * FROM KHOAHOCS;

SELECT * FROM LINHVUCS;

-- XỬ LÝ LỚP HỌC - LOPHOCS

SELECT CONCAT('LH', LPAD(IFNULL(MAX(CAST(SUBSTRING(MALOPHOC, 3, 3) AS UNSIGNED)), 0) + 1, 3, '0')) FROM LOPHOCS; 

SELECT * FROM LOPHOCS;

SELECT * FROM KHOAHOCS;
SELECT * FROM PHONGHOCS;
SELECT * FROM GIANGVIENS;

-- XỬ LÝ HỌC VIÊN - HOCVIENS
SELECT CONCAT('HV', LPAD(IFNULL(MAX(CAST(SUBSTRING(MAHOCVIEN, 3, 3) AS UNSIGNED)), 0) + 1, 3, '0')) FROM HOCVIENS; 

SELECT * FROM HOCVIENS;
       

