CREATE TABLE THANHTOANS (
    MAGIAODICH VARCHAR(255) PRIMARY KEY,
    LOAIGIAODICH ENUM('THU', 'CHI') NOT NULL,
    SOTIEN DOUBLE NOT NULL,
    NGAYTHUCHIEN DATE NOT NULL,
    MAHOCVIEN VARCHAR(255),
    MAKHOAHOC VARCHAR(255),
    PHUONGTHUCTHANHTOAN ENUM('TIEN_MAT', 'CHUYEN_KHOAN', 'VNPAY') NOT NULL,
    TRANGTHAI ENUM('CHO_XU_LY', 'DA_HOAN_THANH', 'THAT_BAI') DEFAULT 'CHO_XU_LY',
    MOTA TEXT,
    NGUOITAO VARCHAR(255)
);

ALTER TABLE THANHTOANS
ADD CONSTRAINT FK_THANHTOANS_HOCVIENS
FOREIGN KEY (MAHOCVIEN) REFERENCES HOCVIENS(MATAIKHOAN);

ALTER TABLE THANHTOANS
ADD CONSTRAINT FK_THANHTOANS_KHOAHOCS
FOREIGN KEY (MAKHOAHOC) REFERENCES KHOAHOCS(MAKHOAHOC);

ALTER TABLE THANHTOANS
ADD CONSTRAINT FK_THANHTOANS_NHANVIENS
FOREIGN KEY (NGUOITAO) REFERENCES NHANVIENS(MANHANVIEN);

