ALTER TABLE PHIEUCHIS
ADD CONSTRAINT FK_PHIEUCHIS_NHANVIENKETOANS
FOREIGN KEY (MAKETOANVIEN) REFERENCES NHANVIENKETOANS(MANHANVIEN);

ALTER TABLE PHIEUTHUS
ADD CONSTRAINT FK_PHIEUTHUS_NHANVIENKETOANS
FOREIGN KEY (MAKETOANVIEN) REFERENCES NHANVIENKETOANS(MANHANVIEN);

ALTER TABLE LOPHOCS
ADD CONSTRAINT FK_LOPHOCS_KHOAHOCS
FOREIGN KEY (MAKHOAHOC) REFERENCES KHOAHOCS(MAKHOAHOC);

ALTER TABLE LOPHOCS
ADD CONSTRAINT FK_LOPHOCS_PHONGHOCS
FOREIGN KEY (MAPHONGHOC) REFERENCES PHONGHOCS(MAPHONGHOC);

ALTER TABLE LOPHOCS
ADD CONSTRAINT FK_LOPHOCS_GIANGVIENS
FOREIGN KEY (MAGIANGVIEN) REFERENCES GIANGVIENS(MAGIANGVIEN);

--
ALTER TABLE GIANGVIENS
ADD CONSTRAINT FK_GIANGVIENS_LINHVUCS
FOREIGN KEY (MALINHVUC) REFERENCES LINHVUCS(MALINHVUC);

ALTER TABLE GIANGVIENS
DROP FOREIGN KEY FK_GIANGVIENS_LINHVUCS;

ALTER TABLE GIANGVIENS
ADD CONSTRAINT FK_GIANGVIENS_LINHVUCS
FOREIGN KEY (MALINHVUC) REFERENCES linhvucs(MALINHVUC)
ON DELETE CASCADE;
--

ALTER TABLE KHOAHOCS
ADD CONSTRAINT FK_KHOAHOCS_LINHVUCS
FOREIGN KEY (MALINHVUC) REFERENCES LINHVUCS(MALINHVUC);

-- SỬA LẠI LOGIC KHI NỐI KHOAHOCS và LINHVUCS
ALTER TABLE KHOAHOCS DROP FOREIGN KEY FK_KHOAHOCS_LINHVUCS;

ALTER TABLE KHOAHOCS ADD CONSTRAINT FK_KHOAHOCS_LINHVUCS
FOREIGN KEY (MALINHVUC) REFERENCES LINHVUCS(MALINHVUC) 
ON DELETE SET NULL;
--

ALTER TABLE CONGTACVIENS
ADD CONSTRAINT FK_CONGTACVIENS_NHANVIENS
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIENS(MANHANVIEN);

ALTER TABLE TAIKHOANS
ADD CONSTRAINT FK_TAIKHOANS_NHANVIENS
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIENS(MANHANVIEN);

ALTER TABLE HOCVIENS
ADD CONSTRAINT FK_HOCVIENS_KHOAHOCS1
FOREIGN KEY (KHOAHOCQUANTAM1) REFERENCES KHOAHOCS(MAKHOAHOC);

ALTER TABLE HOCVIENS
ADD CONSTRAINT FK_HOCVIENS_KHOAHOCS2
FOREIGN KEY (KHOAHOCQUANTAM2) REFERENCES KHOAHOCS(MAKHOAHOC);

-- Xóa 2 khóa ngoại FK_HOCVIENS_KHOAHOCS2 và FK_HOCVIENS_KHOAHOCS1
ALTER TABLE HOCVIENS  
DROP FOREIGN KEY FK_HOCVIENS_KHOAHOCS1;  

ALTER TABLE HOCVIENS  
DROP FOREIGN KEY FK_HOCVIENS_KHOAHOCS2;  
--

ALTER TABLE CHITIETLOPHOCS
ADD CONSTRAINT FK_CHITIETLOPHOCS_HOCVIENS
FOREIGN KEY (MAHOCVIEN) REFERENCES HOCVIENS(MAHOCVIEN);

ALTER TABLE CHITIETLOPHOCS
ADD CONSTRAINT FK_CHITIETLOPHOCS_LOPHOCS
FOREIGN KEY (MALOPHOC) REFERENCES LOPHOCS(MALOPHOC);

-- 
ALTER TABLE THISINHDUTHIS
ADD CONSTRAINT FK_THISINHDUTHIS_LICHTHIS
FOREIGN KEY (MALICHTHI) REFERENCES LICHTHIS(MALICHTHI);

ALTER TABLE THISINHDUTHIS
DROP FOREIGN KEY FK_THISINHDUTHIS_LICHTHIS;

ALTER TABLE THISINHDUTHIS
ADD CONSTRAINT FK_THISINHDUTHIS_LICHTHIS
FOREIGN KEY (MALICHTHI) REFERENCES lichthis(MALICHTHI)
ON DELETE CASCADE;
--

ALTER TABLE THISINHDUTHIS
ADD CONSTRAINT FK_THISINHDUTHIS_PHONGHOCS
FOREIGN KEY (MAPHONGTHI) REFERENCES PHONGHOCS(MAPHONGHOC);

ALTER TABLE LICHTHIS
ADD CONSTRAINT FK_LICHTHIS_LINHVUCS
FOREIGN KEY (MALINHVUC) REFERENCES LINHVUCS(MALINHVUC);

ALTER TABLE NHANVIENS 
ADD CONSTRAINT FK_NHANVIENS_CHUCVUS 
FOREIGN KEY (MACHUCVU) REFERENCES CHUCVUS(MACHUCVU);

-- ALTER

ALTER TABLE LOPHOCS DROP FOREIGN KEY FK_LOPHOCS_GIANGVIENS;
ALTER TABLE CHITIETLOPHOCS DROP FOREIGN KEY FK_CHITIETLOPHOCS_HOCVIENS;

--
CREATE INDEX idx_maHocVien ON HOCVIENS(MAHOCVIEN);

ALTER TABLE CHITIETLOPHOCS
ADD CONSTRAINT FK_CHITIETLOPHOCS_HOCVIENS
FOREIGN KEY (MAHOCVIEN) REFERENCES HOCVIENS(MAHOCVIEN);
--

ALTER TABLE GIANGVIENS DROP PRIMARY KEY;
ALTER TABLE HOCVIENS DROP PRIMARY KEY;

--
ALTER TABLE GIANGVIENS 
ADD COLUMN MATAIKHOAN VARCHAR(255) NOT NULL UNIQUE,
ADD CONSTRAINT FK_GIANGVIENS_TAIKHOANS FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOANS(MATAIKHOAN);
--

ALTER TABLE GIANGVIENS 
MODIFY COLUMN MATAIKHOAN VARCHAR(255) UNIQUE DEFAULT NULL;

ALTER TABLE HOCVIENS 
ADD COLUMN MATAIKHOAN VARCHAR(255) NOT NULL UNIQUE,
ADD CONSTRAINT PK_HOCVIENS PRIMARY KEY (MATAIKHOAN),
ADD CONSTRAINT FK_HOCVIENS_TAIKHOANS FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOANS(MATAIKHOAN);

-- XÓA MATAIKHOAN LÀM PK
ALTER TABLE HOCVIENS DROP CONSTRAINT FK_HOCVIENS_TAIKHOANS;	
ALTER TABLE HOCVIENS DROP COLUMN MATAIKHOAN;

ALTER TABLE HOCVIENS 
ADD COLUMN MATAIKHOAN VARCHAR(255) DEFAULT NULL,
ADD CONSTRAINT FK_HOCVIENS_TAIKHOANS FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOANS(MATAIKHOAN);
--

-- SỬA LẠI REFER TỚI GIANGVIENS(MAGIANGVIEN)
ALTER TABLE LOPHOCS 
ADD CONSTRAINT FK_LOPHOCS_GIANGVIENS 
FOREIGN KEY (MAGIANGVIEN) REFERENCES GIANGVIENS(MATAIKHOAN);

ALTER TABLE LOPHOCS DROP FOREIGN KEY FK_LOPHOCS_GIANGVIENS;

ALTER TABLE LOPHOCS 
ADD CONSTRAINT FK_LOPHOCS_GIANGVIENS 
FOREIGN KEY (MAGIANGVIEN) REFERENCES GIANGVIENS(MAGIANGVIEN) 
ON DELETE SET NULL;
--

ALTER TABLE CHITIETLOPHOCS 
ADD CONSTRAINT FK_CHITIETLOPHOCS_HOCVIENS 
FOREIGN KEY (MAHOCVIEN) REFERENCES HOCVIENS(MATAIKHOAN);

-- SỬA LẠI LÀ NULLABLE
ALTER TABLE LOPHOCS 
ADD COLUMN MANHANVIEN VARCHAR(255) NOT NULL,
ADD CONSTRAINT FK_LOPHOCS_NHANVIENS FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIENS(MANHANVIEN);

ALTER TABLE LOPHOCS DROP CONSTRAINT FK_LOPHOCS_NHANVIENS;	
ALTER TABLE LOPHOCS DROP COLUMN MANHANVIEN;

ALTER TABLE LOPHOCS 
ADD COLUMN MANHANVIEN VARCHAR(255) DEFAULT NULL;

ALTER TABLE LOPHOCS 
ADD CONSTRAINT FK_LOPHOCS_NHANVIENS 
FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIENS(MANHANVIEN);
--

ALTER TABLE BAIVIETS 
ADD CONSTRAINT FK_BAIVIETS_NHANVIENS 
FOREIGN KEY (NGUOIVIETBAI) REFERENCES NHANVIENS(MANHANVIEN);

ALTER TABLE HOCVIENS 
ADD CONSTRAINT FK_HOCVIENS_NHANVIENS 
FOREIGN KEY (NGUOINHAPTHONGTIN) REFERENCES NHANVIENS(MANHANVIEN); 

-- ĐỂ CODE XONG HẾT RỒI NHÌN LẠI PHẦN NÀY
ALTER TABLE HOCVIENS 
DROP CONSTRAINT FK_HOCVIENS_NHANVIENS;
--
