spring:
  application:
    name: DATN
  datasource:
    url: jdbc:mysql://localhost:3306/DATN?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: TA1NW75G
    secretKey: FCSR6TSRXUHO7FUAQ7UCTZV8DW7YCZW6
    returnUrl: http://localhost:8080/api/vnpay/return
    version: 2.1.0
    command: pay
    orderType: other


